const routes = [
  {
    id: "main",
    sourcePath: "index.html",
    publicPath: "/",
    indexable: true,
    canonicalIntent: "self",
    sitemap: true,
  },
  {
    id: "switchboard",
    sourcePath: "switchboard.html",
    publicPath: "/switchboard.html",
    indexable: false,
    canonicalIntent: "none",
    sitemap: false,
  },
  {
    id: "templates",
    sourcePath: "templates/index.html",
    publicPath: "/templates/",
    indexable: true,
    canonicalIntent: "self",
    sitemap: true,
  },
  {
    id: "templateGallery",
    sourcePath: "templates/template-gallery/index.html",
    publicPath: "/templates/template-gallery/index.html",
    indexable: false,
    canonicalIntent: "none",
    sitemap: false,
  },
  {
    id: "transportationCaseStudy",
    sourcePath: "work/transportation-solutions-lighting.html",
    publicPath: "/work/transportation-solutions-lighting.html",
    indexable: true,
    canonicalIntent: "self",
    sitemap: true,
  },
  {
    id: "codeLinkCaseStudy",
    sourcePath: "work/codelink.html",
    publicPath: "/work/codelink.html",
    indexable: true,
    canonicalIntent: "self",
    sitemap: true,
  },
  {
    id: "redeemedHandsCaseStudy",
    sourcePath: "work/redeemed-hands.html",
    publicPath: "/work/redeemed-hands.html",
    indexable: true,
    canonicalIntent: "self",
    sitemap: true,
  },
  {
    id: "privacy",
    sourcePath: "privacy.html",
    publicPath: "/privacy.html",
    indexable: false,
    canonicalIntent: "self",
    sitemap: false,
  },
  {
    id: "terms",
    sourcePath: "terms.html",
    publicPath: "/terms.html",
    indexable: false,
    canonicalIntent: "self",
    sitemap: false,
  },
  {
    id: "notFound",
    sourcePath: "404.html",
    publicPath: "/404.html",
    indexable: false,
    canonicalIntent: "none",
    sitemap: false,
  },
];

module.exports = routes;
