(()=>{
  const menu=document.querySelector('[data-menu]'),nav=document.querySelector('.site-header nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
  const pause=document.querySelector('[data-pause]');pause?.addEventListener('click',()=>{const media=pause.closest('.hero-media'),paused=media.classList.toggle('paused');pause.setAttribute('aria-pressed',String(paused));pause.querySelector('i').className=`ph ph-${paused?'play':'pause'}`;pause.querySelector('span').textContent=paused?'Resume motion':'Pause motion'});
  const phases={
    precon:{number:'PHASE 01',title:'Price the buildable scope.',copy:'Budget, constructability, long-lead items, and schedule risk are surfaced while options still exist.',input:'Design documents + milestone schedule',output:'Scope narrative + risk log',src:'assets/media/phase-preconstruction.jpg',alt:'Preconstruction team reviewing mechanical plans and a milestone schedule beside an active commercial project'},
    coord:{number:'PHASE 02',title:'Resolve it before the field.',copy:'Trade paths, access zones, elevations, sleeves, and equipment clearances become shared installation information.',input:'Federated model + field input',output:'Approved coordination zones',src:'assets/media/phase-coordination.jpg',alt:'MEP coordination team reviewing a detailed commercial building systems model'},
    fab:{number:'PHASE 03',title:'Move repeatable work off site.',copy:'Assemblies are planned around transport, access, lifting, and the installation sequence.',input:'Approved spool drawings',output:'Labeled install-ready assemblies',src:'assets/media/phase-fabrication.jpg',alt:'Commercial prefabrication shop assembling labeled modular pipe racks'},
    install:{number:'PHASE 04',title:'Run the plan with the crew.',copy:'Look-ahead planning connects material releases, inspections, access, and downstream constraints.',input:'Coordination package + releases',output:'Installed and tested systems',src:'assets/media/phase-installation.jpg',alt:'Commercial mechanical crew installing coordinated overhead piping from a protected lift'},
    commission:{number:'PHASE 05',title:'Verify performance by system.',copy:'Testing, startup, correction, and owner requirements are tracked with the installed work.',input:'Completed systems + test plan',output:'Verified readiness records',src:'assets/media/phase-commissioning.jpg',alt:'Commissioning technician testing completed commercial mechanical equipment'},
    close:{number:'PHASE 06',title:'Finish with usable records.',copy:'As-builts, test reports, O&M inputs, and turnover items are assembled throughout delivery.',input:'Field records + approvals',output:'Organized closeout package',src:'assets/media/phase-closeout.jpg',alt:'Project team assembling closeout documents and digital system records'}
  };
  const tabs=[...document.querySelectorAll('[data-phase]')],panel=document.getElementById('phase-panel'),image=document.querySelector('[data-phase-image]');
  function selectPhase(button){const data=phases[button.dataset.phase];tabs.forEach(tab=>{const active=tab===button;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});panel.setAttribute('aria-labelledby',button.id);image.parentElement.classList.add('changing');setTimeout(()=>{image.src=data.src;image.alt=data.alt;image.parentElement.classList.remove('changing')},180);['number','title','copy','input','output'].forEach(key=>document.querySelector(`[data-phase-${key}]`).textContent=data[key])}
  tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectPhase(tab));tab.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();let next=index;if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else next=(index+(['ArrowDown','ArrowRight'].includes(event.key)?1:-1)+tabs.length)%tabs.length;tabs[next].focus();selectPhase(tabs[next])})});
  const form=document.querySelector('[data-form]');form?.addEventListener('submit',event=>{event.preventDefault();let valid=true;form.querySelectorAll('[required]').forEach(field=>{let message=field.value.trim()?'':'Required.';if(!message&&field.type==='email'&&!/^\S+@\S+\.\S+$/.test(field.value))message='Enter a valid email.';form.querySelector(`[data-error="${field.name}"]`).textContent=message;field.setAttribute('aria-invalid',String(Boolean(message)));valid=valid&&!message});const status=form.querySelector('.form-status');if(!valid){status.textContent='Review the highlighted fields.';form.querySelector('[aria-invalid="true"]')?.focus();return}status.textContent='Bid invitation captured for this demo. Connect a secure endpoint before launch.';form.reset()});
})();
