import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const routes = require("../config/routes.cjs");
const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const sitemapPath = fileURLToPath(new URL("../sitemap.xml", import.meta.url));
const siteOrigin = "https://www.networksandnodes.org";

const escapeXml = (value) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");

const sitemapRoutes = routes.filter((route) => route.sitemap);

for (const route of sitemapRoutes) {
  if (!route.indexable) {
    throw new Error(`Sitemap route ${route.id} must be indexable.`);
  }

  if (route.canonicalIntent !== "self") {
    throw new Error(`Sitemap route ${route.id} must have a self-canonical intent.`);
  }

  if (!route.publicPath.startsWith("/")) {
    throw new Error(`Sitemap route ${route.id} must use an absolute public path.`);
  }
}

const entries = sitemapRoutes
  .map((route) => {
    const absoluteUrl = new URL(route.publicPath, siteOrigin).href;
    return `  <url>\n    <loc>${escapeXml(absoluteUrl)}</loc>\n  </url>`;
  })
  .join("\n\n");

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from config/routes.cjs. Do not edit this file by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;

await writeFile(sitemapPath, sitemap, "utf8");

process.stdout.write(
  `Generated ${sitemapRoutes.length} sitemap URLs from ${repositoryRoot}config/routes.cjs.\n`,
);
