(()=>{
  const menu=document.querySelector('[data-menu]'),nav=document.querySelector('header nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
  const projects={
    harbor:{title:'Harbor House',location:'West Palm Beach / Flagler waterfront',strategy:'Ground-up mixed use',stage:'Preconstruction / pricing',gate:'Reconcile 50% DD estimate',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1500&q=86',alt:'Harbor House architectural direction'},
    foundry:{title:'The Foundry Court',location:'Delray Beach / Pineapple Grove edge',strategy:'Adaptive reuse + retail',stage:'Concept / due diligence',gate:'Complete existing-condition survey',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1500&q=86',alt:'Foundry Court adaptive reuse courtyard direction'},
    canal:{title:'Canal Row',location:'Lake Worth Beach / canal district',strategy:'Waterfront multifamily',stage:'Planning / entitlement',gate:'Confirm setback + public edge',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1500&q=86',alt:'Canal Row waterfront multifamily direction'}
  };
  document.querySelectorAll('[data-map]').forEach(button=>button.addEventListener('click',()=>{const p=projects[button.dataset.map],image=document.querySelector('[data-map-image]');document.querySelectorAll('[data-map]').forEach(b=>b.classList.toggle('active',b===button));image.style.opacity='.2';setTimeout(()=>{image.src=p.image;image.alt=p.alt;image.style.opacity='1'},180);['title','location','strategy','stage','gate'].forEach(key=>document.querySelector(`[data-map-${key}]`).textContent=p[key])}));
  const form=document.querySelector('[data-form]');form?.addEventListener('submit',e=>{e.preventDefault();let valid=true;form.querySelectorAll('[required]').forEach(field=>{let message=field.value.trim()?'':'Required.';if(!message&&field.type==='email'&&!/^\S+@\S+\.\S+$/.test(field.value))message='Enter a valid email.';form.querySelector(`[data-error="${field.name}"]`).textContent=message;field.setAttribute('aria-invalid',String(Boolean(message)));valid=valid&&!message});const status=form.querySelector('.form-status');if(!valid){status.textContent='Review the highlighted fields.';return}status.textContent='Request captured for this fictional concept.';form.reset()});
})();
